# Generated by Django 5.1.2 on 2024-10-25 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kafedra',
            name='xodimlar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fakultet',
            name='kafedralar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.kafedra'),
        ),
        migrations.AddField(
            model_name='fakultet',
            name='lokatsiya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.lokatsiya'),
        ),
        migrations.AddField(
            model_name='rektorad',
            name='fakultet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.fakultet'),
        ),
        migrations.AddField(
            model_name='rektorad',
            name='xodim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='yonalish',
            name='qabul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.qabul'),
        ),
        migrations.AddField(
            model_name='kafedra',
            name='yonalishlar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.yonalish'),
        ),
    ]
